apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: akspoc
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /akspoc
        backend:
          service:
            name: akspoc
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: akspoc
spec:
  selector:
    app: akspoc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: akspoc
  labels:
    app: akspoc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: akspoc
  template:
    metadata:
      labels:
        app: akspoc
    spec:
      containers:
      - name: akspoc
        image: <yourACRname>.azurecr.io/akspoc
        ports:
        - containerPort: 8080